[package]
name = "xross-core"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
xross-metadata.path = "../xross-metadata"
